server {
    listen 8080;
    server_name localhost;
    client_max_body_size 100;
    root ./YoupiBanane;

    location / {
        allow_methods GET;
        index youpi.bad_extension;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    location /directory {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        cgi_extension .bla;
        cgi_path /home/rub/Desktop/webserv/www/cgi-bin/cgi_test;
        client_max_body_size 150000000;
    }
}
