server {
    listen 127.0.0.1:8080;
    server_name localhost;

    root ./www/site1;
    index index.html index.htm;

    client_max_body_size 10M;



    location / {
        allow_methods GET;
        root ./www/site1;
        index index.html;
        autoindex off;
    }

    location /public {
        allow_methods GET;
        root ./www/site1;
        index index.html;
        autoindex on;
    }

    location /form {
        allow_methods GET POST;
        root ./www/site1;
        index form.html;
        autoindex off;
    }

    location /upload {
        allow_methods GET POST DELETE;
        root ./www/site1;
        index upload.html;
        autoindex on;

 #       upload_enable on;
#        upload_store ./www/site1/uploads;
    }

    location /old-page {
        allow_methods GET;
    #    return 301 /new-page;
    }

    location /new-page {
        allow_methods GET;
        root ./www/site1;
        index new-page.html;
        autoindex off;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root ./www/site1;

    #    cgi_extension .py;
    #    cgi_path /usr/bin/python3;

        index test.py;
        autoindex off;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name second.local;

    root ./www/site2;
    index index.html;

    client_max_body_size 2M;

    error_page 404 ./www/errors/404.html;
    error_page 500 ./www/errors/500.html;

    location / {
        allow_methods GET;
        root ./www/site2;
        index index.html;
        autoindex off;
    }

    location /files {
        allow_methods GET;
        root ./www/site2;
        autoindex on;
    }

    location /redirect {
        allow_methods GET;
    #    return 302 /;
    }

    location /cgi {
        allow_methods GET POST;
        root ./www/site2;

    #    cgi_extension .py;
    #    cgi_path /usr/bin/python3;

        autoindex off;
    }
}
