server {
    listen 8080;
    root ./configs/allow_methods/www;

    location / {
        index index.html;
        allow_methods GET;
    }

    location /open {
        index index.html;
        allow_methods GET POST DELETE;
    }
}
