server {
    listen 8093;
    root /var/www/html;

    location / {
        index index.html;
    }
}

server {
    listen 8093;
    root /var/www/public;

    location /api {
        index index.php;
    }
}
