server {
    listen 8080;
    root ./configs/location_matching/www;

    location / {
        index index.html;
        allow_methods GET;
    }

    location /deep/nested {
        root ./configs/location_matching/www_override;
        index index.html;
        allow_methods GET;
    }
}
