server {
    listen 8080;
    root ./configs/redirect/www;

    location / {
        index index.html;
        allow_methods GET;
    }

    location /old {
        return 301 /new/;
    }

    location /new {
        index index.html;
        allow_methods GET;
    }
}
