server {
    listen 127.0.0.1:8080;
    server_name localhost;

    root ./www/site1;

    location / {
        index first.html second.html third.html;
    }

    location /old-page {
        return 301 /;
    }
}
