server {
    listen 8080;
    root ./configs/multi_port/site1;

    location / {
        index index.html;
        allow_methods GET;
    }
}

server {
    listen 8081;
    root ./configs/multi_port/site2;

    location / {
        index index.html;
        allow_methods GET;
    }
}
